# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  # - job_name: app
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['host.docker.internal:8000']

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
         - targets: ['localhost:9090']

  - job_name: "spark_master" 
    scrape_interval: "5s"
    metrics_path: "/metrics/master/prometheus/"
    static_configs:
        - targets: ['spark:8080']

  - job_name: "jmx" 
    scrape_interval: "5s"
    static_configs:
        - targets: ['spark:9999', 'spark-worker-1:9999']

  - job_name: "spark_worker"
    scrape_interval: "5s"
    metrics_path: "/metrics/prometheus/"
    static_configs:
        - targets: ['spark-worker-1:8081']

  - job_name: "driver"
    scrape_interval: "5s"
    metrics_path: "/metrics/prometheus/"
    static_configs:
        - targets: ['spark-worker-1:4040']

  - job_name: "executor"
    scrape_interval: "5s"
    metrics_path: "/metrics/executors/prometheus/"
    static_configs:
        - targets: ['spark-worker-1:4040']

  - job_name: "node"
    scrape_interval: "5s"
    static_configs:
        - targets: ['spark-worker-1:9100', 'spark:9100']

